### ISSUE TITLE
rpm: missing Python dependency

### ISSUE THREAD

**Issue by JanneKataja-TomTom** [scalyr/scalyr-agent-2#628]
rpm `scalyr-agent-2` does not list dependency for Python 2 or 3. I see that it works with both Python 2 and Python 3. rpm allows alternative `Requires` dependencies, for example either Python 2 OR Python 3. See: 
https://rpm.org/user_doc/boolean_dependencies.html

**Comment by ArthurKamalov** [comment]
Hi, @JanneKataja-TomTom Since Python 2 has reached its EOL one of our goals for the nearest future is to fully switch to Python 3, so this issue should be solved as well.  For now, unfortunately, our packaging tool - `fpm` does not provide the ability to specify boolean dependencies for the rpm packages.  This year we also plan on moving to distribution-specific releases which should be able to address this problem.
